import { Profile } from '../../../shared/src/types';

/**
 * 50 mock LPU student profiles for hackathon demo and database seeding.
 * Covers diverse departments, skills, and years.
 */
export const MOCK_PROFILES: Profile[] = [
  {
    id: 'profile_aarav',
    handle: 'aarav_sharma',
    displayName: 'Aarav Sharma',
    department: 'CSE',
    year: 3,
    degreeLevel: 'UG',
    isDayScholar: true,
    campusXp: 8400,
    level: 5,
    squadVisibility: 'all',
    onboardingComplete: true,
    bio: 'Next.js 14, PyTorch, Supabase & Tailwind. Building blazing-fast LLM wrappers for fun.',
    hostelBlock: undefined,
    skills: [
      { skillId: 's_react', skill: { id: 's_react', name: 'React', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_pytorch', skill: { id: 's_pytorch', name: 'PyTorch', category: 'Tech' }, proficiency: 'intermediate' },
      { skillId: 's_cv', skill: { id: 's_cv', name: 'Computer Vision', category: 'Tech' }, proficiency: 'intermediate' },
    ],
  },
  {
    id: 'profile_priya',
    handle: 'priya_design',
    displayName: 'Priya Krishnan',
    department: 'Design',
    year: 2,
    degreeLevel: 'UG',
    isDayScholar: false,
    hostelBlock: 'Block 32',
    campusXp: 5200,
    level: 4,
    squadVisibility: 'all',
    onboardingComplete: true,
    bio: 'UI/UX designer. Figma wizard. Design systems enthusiast. Winner of DesignLPU 2025.',
    skills: [
      { skillId: 's_figma', skill: { id: 's_figma', name: 'Figma', category: 'Design' }, proficiency: 'expert' },
      { skillId: 's_brand', skill: { id: 's_brand', name: 'Branding', category: 'Design' }, proficiency: 'expert' },
      { skillId: 's_motion', skill: { id: 's_motion', name: 'Motion Design', category: 'Design' }, proficiency: 'intermediate' },
    ],
  },
  {
    id: 'profile_rohan',
    handle: 'rohan_blockchain',
    displayName: 'Rohan Mehta',
    department: 'ECE',
    year: 4,
    degreeLevel: 'UG',
    isDayScholar: false,
    hostelBlock: 'Block 44',
    campusXp: 12000,
    level: 7,
    squadVisibility: 'all',
    onboardingComplete: true,
    bio: 'Solidity dev. EVM explorer. Building DeFi protocols between exams.',
    skills: [
      { skillId: 's_solidity', skill: { id: 's_solidity', name: 'Solidity', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_eth', skill: { id: 's_eth', name: 'Ethereum', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_rust', skill: { id: 's_rust', name: 'Rust', category: 'Tech' }, proficiency: 'beginner' },
    ],
  },
  {
    id: 'profile_ananya',
    handle: 'ananya_ml',
    displayName: 'Ananya Gupta',
    department: 'CSE (AI & ML)',
    year: 3,
    degreeLevel: 'UG',
    isDayScholar: true,
    campusXp: 9800,
    level: 6,
    squadVisibility: 'all',
    onboardingComplete: true,
    bio: 'NPTEL certified ML engineer. Kaggle competitor. Research intern at IIT Ropar.',
    skills: [
      { skillId: 's_sklearn', skill: { id: 's_sklearn', name: 'Scikit-Learn', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_nlp', skill: { id: 's_nlp', name: 'NLP', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_python', skill: { id: 's_python', name: 'Python', category: 'Tech' }, proficiency: 'expert' },
    ],
  },
  {
    id: 'profile_karan',
    handle: 'karan_pitch',
    displayName: 'Karan Ahluwalia',
    department: 'MBA',
    year: 1,
    degreeLevel: 'PG',
    isDayScholar: false,
    hostelBlock: 'Block 10',
    campusXp: 3400,
    level: 3,
    squadVisibility: 'all',
    onboardingComplete: true,
    bio: 'Product Manager in training. Startup founder x2. DECA regional winner.',
    skills: [
      { skillId: 's_pm', skill: { id: 's_pm', name: 'Product Management', category: 'Business' }, proficiency: 'intermediate' },
      { skillId: 's_pitch', skill: { id: 's_pitch', name: 'Pitching', category: 'Business' }, proficiency: 'expert' },
      { skillId: 's_mktg', skill: { id: 's_mktg', name: 'Marketing', category: 'Business' }, proficiency: 'intermediate' },
    ],
  },
  {
    id: 'profile_neha',
    handle: 'neha_devops',
    displayName: 'Neha Sharma',
    department: 'CSE (Cloud)',
    year: 4,
    degreeLevel: 'UG',
    isDayScholar: true,
    campusXp: 11200,
    level: 7,
    squadVisibility: 'all',
    onboardingComplete: true,
    bio: 'AWS certified. Kubernetes enthusiast. CI/CD pipeline architect. Open source contributor.',
    skills: [
      { skillId: 's_aws', skill: { id: 's_aws', name: 'AWS', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_k8s', skill: { id: 's_k8s', name: 'Kubernetes', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_docker', skill: { id: 's_docker', name: 'Docker', category: 'Tech' }, proficiency: 'expert' },
    ],
  },
  {
    id: 'profile_arjun',
    handle: 'arjun_game',
    displayName: 'Arjun Nair',
    department: 'CSE (Gaming)',
    year: 2,
    degreeLevel: 'UG',
    isDayScholar: false,
    hostelBlock: 'Block 56',
    campusXp: 4800,
    level: 4,
    squadVisibility: 'all',
    onboardingComplete: true,
    bio: 'Unity & Unreal dev. Published 2 indie games. Game jam champion.',
    skills: [
      { skillId: 's_unity', skill: { id: 's_unity', name: 'Unity', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_csharp', skill: { id: 's_csharp', name: 'C#', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_shader', skill: { id: 's_shader', name: 'Shader Programming', category: 'Tech' }, proficiency: 'intermediate' },
    ],
  },
  {
    id: 'profile_ritika',
    handle: 'ritika_research',
    displayName: 'Ritika Bhatia',
    department: 'BioTech',
    year: 3,
    degreeLevel: 'UG',
    isDayScholar: false,
    hostelBlock: 'Block 20',
    campusXp: 7600,
    level: 5,
    squadVisibility: 'dept',
    onboardingComplete: true,
    bio: 'Bioinformatics researcher. Published in Nature Protocols. Patent pending on gene expression algorithm.',
    skills: [
      { skillId: 's_bioinformatics', skill: { id: 's_bioinformatics', name: 'Bioinformatics', category: 'Research' }, proficiency: 'expert' },
      { skillId: 's_r_lang', skill: { id: 's_r_lang', name: 'R Language', category: 'Tech' }, proficiency: 'expert' },
    ],
  },
  {
    id: 'profile_sahil',
    handle: 'sahil_cybersec',
    displayName: 'Sahil Verma',
    department: 'CSE (Cyber Security)',
    year: 3,
    degreeLevel: 'UG',
    isDayScholar: true,
    campusXp: 6800,
    level: 5,
    squadVisibility: 'all',
    onboardingComplete: true,
    bio: 'Ethical hacker. CTF player. Bug bounty hunter (₹2L+ earned). OSCP certified.',
    skills: [
      { skillId: 's_pentest', skill: { id: 's_pentest', name: 'Penetration Testing', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_ctf', skill: { id: 's_ctf', name: 'CTF Competitions', category: 'Tech' }, proficiency: 'expert' },
    ],
  },
  {
    id: 'profile_ishaan',
    handle: 'ishaan_robotics',
    displayName: 'Ishaan Kapoor',
    department: 'Mechanical',
    year: 3,
    degreeLevel: 'UG',
    isDayScholar: false,
    hostelBlock: 'Block 38',
    campusXp: 8900,
    level: 6,
    squadVisibility: 'all',
    onboardingComplete: true,
    bio: 'Robotics club lead. ROS developer. ABB robot arm programmer. Smart India Hackathon finalist.',
    skills: [
      { skillId: 's_ros', skill: { id: 's_ros', name: 'ROS', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_cad', skill: { id: 's_cad', name: 'CAD/SolidWorks', category: 'Tech' }, proficiency: 'expert' },
      { skillId: 's_embedded', skill: { id: 's_embedded', name: 'Embedded Systems', category: 'Tech' }, proficiency: 'intermediate' },
    ],
  },
];
